### ISSUE TITLE
Рефактор локализаций

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#107]
Собственно говоря, нужно упростить создание локализаций, чтобы можно было менять максимум 2 файла:

/locales -> *.strings, list.yml

strings остаются как есть, а в `list.yml` будет так:

```yml
list:
    - code: "en"
      flag: "us"
      name: "English"
      native_name: "English"
      author: "Vladimír Barinov (veselcraft)"
    - code: "am"
      flag: "am"
      name: "Armenian"
      native_name: "Հայերեն"
      author: "LifesMinder"
```

Ну и глобальная функция, которая возвращает список языков, и которая этот самый язык и меняет:
`getLanguageList()`
`setLanguage("am")`
